Fix the compilation problem on OSX El Capitan 1. SFMLConfig.cmake was not found. this was fixed to add back the SFML.cmake module 2. Section::Layer cannot compile without a user-provided default constructor [  1%] Building CXX object CMakeFiles/game.dir/Source/World/Chunk/CSection.cpp.o /tmp/HopsonCraft/Source/World/Chunk/CSection.cpp:12:35: error: default initialization of an object       of const type 'const Section::Layer' without a user-provided default constructor     const Section::Layer Section::errorLayer;                                   ^                                             {} 1 error generated.
this was solved by adding an empty constructor to the struct
3. Undefined symbols "getFileNamesFromFolder" originate in File_Util.cpp
this was because the MACRO check did not include __APPLE__ platform to compile.
I added modified the macro #if check to let it compile